(function() {
    var trixFactory = function() {
        var factory = {};

        factory.getTricks = [
            { trick: 'Shuvit',
            salt: false},
            { trick: '5050',
            salt: false },
            { trick: '180 NoComply' ,
            salt: false},
            { trick: 'Bkd-flip',
            salt: false },
            { trick: 'Fs shuvit',
            salt: false },
            { trick: 'Noseslide',
            salt: false },
            { trick: 'BONELESS!!!',
            salt: false },
            { trick: 'Jibb',
            salt: true },
            { trick: 'Någon slags powerslide',
            salt: false },
            { trick: 'kickflip',
            salt: false },
            { trick: 'Något switch',
            salt: false },
            { trick: 'Flamingo',
            salt: true },
            { trick: 'GRINDA BÖJJEN',
            salt: false },
            { trick: "ROCK'n'Roll",
            salt: false },
            { trick: 'Fakie Fliptrix (inte shuvit)',
            salt: false },
            { trick: 'Kickflip i banken',
            salt: false },
            { trick: 'Manual på boxen med en specialare',
            salt: false },
            { trick: '360flip or dont',
            salt: false },
            { trick: 'Gör en stall någonstans',
            salt: false },
            { trick: 'SLAPPY',
            salt: false },
            { trick: 'Nollie-trix!',
            salt: false },
            { trick: 'Ollie över något',
            salt: false },
            { trick: 'Todd Falcon speziale',
            salt: true },
            { trick: 'Nollie kickflip',
            salt: false },
            { trick: 'VALFRITT TRICK',
            salt: false },
            { trick: 'Ta mer fart',
            salt: false },
            { trick: 'SNABBAREEEE',
            salt: false },
            { trick: 'Dylan Rieder-landning (RIP)',
            salt: false },
            { trick: 'Wallie',
            salt: false },
            { trick: 'Bs 180 trix',
            salt: false },
            { trick: 'Bs grind',
            salt: false },
            { trick: 'Fs grind',
            salt: false },
            { trick: 'Bs slide',
            salt: false },
            { trick: 'Fs slide',
            salt: false },
            { trick: 'Fakie 180 trix',
            salt: false },
            { trick: 'no push line + valfritt flattrick',
            salt: false },
            { trick: 'powerslide shove it',
            salt: false },
            { trick: 'no comply över något',
            salt: false },
            { trick: 'rip it n sniff it',
            salt: true },
            { trick: 'ben gore-it',
            salt: true },
            { trick: 'ostpinne',
            salt: true },
            { trick: 'valfri no comply',
            salt: false },
            { trick: 'valfri no comply',
            salt: false },
            { trick: 'valfri no comply',
            salt: false },
            { trick: 'charlie chaplin flip',
            salt: false },
            { trick: 'rätta till ett plagg mid-line',
            salt: true },
            { trick: 'fixa frillan',
            salt: false },
            { trick: 'nosestall/tailstall sex change',
            salt: false },
            { trick: 'sex change',
            salt: false },
            { trick: '3 snabba ollies',
            salt: false },
            { trick: 'något från 90-talet',
            salt: false },
            { trick: 'köp en tuborg och två pølse',
            salt: true },
            { trick: 'sug i dig en pepsi',
            salt: true },
            { trick: 'tänd en cigg',
            salt: true },
            { trick: 'kolla din beeper',
            salt: true },
            { trick: 'ryck upp byxan från under hälen',
            salt: true },
            { trick: 'sudda',
            salt: false },
            { trick: 'snabbareee',
            salt: false },
            { trick: 'roast beef på flat',
            salt: true },
            { trick: 'switch nollie',
            salt: false },
            { trick: 'bs 360 (skoja)',
            salt: false },
            { trick: 'sproing',
            salt: true },
            { trick: 'pizza guy',
            salt: true },
            { trick: 'obligatorisk no comply' ,
            salt: false},
            { trick: 'neka toedrag',
            salt: true },
            { trick: 'skrik en svordom',
            salt: false },
            { trick: 'viska en hemlis + flattrick',
            salt: false },
            { trick: 'tänk på ett ex + highest ollie',
            salt: true },
            { trick: 'droppa valfri j.casanova-line',
            salt: true },
            { trick: 'anklaga filmaren för headcut',
            salt: true },
            { trick: 'eurodisco som musikval till din edit',
            salt: true },
            { trick: 'bomma en cigg av en local',
            salt: true },
            { trick: 'shop homie 4 a day',
            salt: true },
            { trick: 'kiss the rail boardslide',
            salt: false },
            { trick: 'kiss the rail boardslide 2 fakie',
            salt: false },
            { trick: 'bs slide 2 fakie',
            salt: false },
            { trick: 'fs slide 2 fakie',
            salt: false },
            { trick: 'skjut en snut alt. freestyletrick',
            salt: true },
            { trick: 'gör en heelflip, kalla den för dark kickflip',
            salt: true },
            { trick: 'övertyga nån att det heter inward kickflip, inte hardflip',
            salt: true },
            { trick: 'tyck att kickbike är rätt gött ändå',
            salt: true }
        ];
        return factory;
    };

    angular.module('listopheApp').factory('trixFactory', trixFactory);

})();
